// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.3
// Project name: wifi_demo

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui_Screen1;
lv_obj_t * ui_wifiConnectBtn;
lv_obj_t * ui_labelSearchNetwork;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Dropdown2;
lv_obj_t * ui_TextArea2;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
void ui_event_Connect(lv_event_t * e);
lv_obj_t * ui_Connect;
void ui_event_labelSearchNetwork1(lv_event_t * e);
lv_obj_t * ui_labelSearchNetwork1;
lv_obj_t * ui_Keyboard2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Connect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 1000, 0);
    }
}
void ui_event_labelSearchNetwork1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
    }
}

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x909EA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiConnectBtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_wifiConnectBtn, 192);
    lv_obj_set_height(ui_wifiConnectBtn, 54);
    lv_obj_set_x(ui_wifiConnectBtn, -122);
    lv_obj_set_y(ui_wifiConnectBtn, -83);
    lv_obj_set_align(ui_wifiConnectBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiConnectBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiConnectBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_recolor(ui_wifiConnectBtn, lv_color_hex(0x27D2F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_wifiConnectBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifiConnectBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifiConnectBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifiConnectBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_wifiConnectBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiConnectBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifiConnectBtn, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSearchNetwork = lv_label_create(ui_wifiConnectBtn);
    lv_obj_set_width(ui_labelSearchNetwork, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSearchNetwork, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelSearchNetwork, 1);
    lv_obj_set_y(ui_labelSearchNetwork, -2);
    lv_obj_set_align(ui_labelSearchNetwork, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSearchNetwork, "Scan Networks");

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 1);
    lv_obj_set_y(ui_Label1, -146);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "WiFi Connection");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown2 = lv_dropdown_create(ui_Screen1);
    lv_obj_set_width(ui_Dropdown2, 244);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 96);
    lv_obj_set_y(ui_Dropdown2, -9);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Dropdown2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea2, 240);
    lv_obj_set_height(ui_TextArea2, 46);
    lv_obj_set_x(ui_TextArea2, 95);
    lv_obj_set_y(ui_TextArea2, 55);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_wifi_search_sized_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 42);
    lv_obj_set_y(ui_Image1, -84);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -77);
    lv_obj_set_y(ui_Label2, -5);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "SSID : ");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -116);
    lv_obj_set_y(ui_Label3, 57);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "PASSWORD : ");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Connect = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Connect, 192);
    lv_obj_set_height(ui_Connect, 54);
    lv_obj_set_x(ui_Connect, 5);
    lv_obj_set_y(ui_Connect, 131);
    lv_obj_set_align(ui_Connect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Connect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_recolor(ui_Connect, lv_color_hex(0x27D2F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Connect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Connect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Connect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Connect, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSearchNetwork1 = lv_label_create(ui_Connect);
    lv_obj_set_width(ui_labelSearchNetwork1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSearchNetwork1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelSearchNetwork1, 1);
    lv_obj_set_y(ui_labelSearchNetwork1, -2);
    lv_obj_set_align(ui_labelSearchNetwork1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSearchNetwork1, "Connect");

    ui_Keyboard2 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard2, 469);
    lv_obj_set_height(ui_Keyboard2, 192);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, -78);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_labelSearchNetwork1, ui_event_labelSearchNetwork1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Connect, ui_event_Connect, LV_EVENT_ALL, NULL);

}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
