// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.3
// Project name: wifi_demo

#ifndef _WIFI_DEMO_UI_H
#define _WIFI_DEMO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_wifiConnectBtn;
extern lv_obj_t * ui_labelSearchNetwork;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
void ui_event_Connect(lv_event_t * e);
extern lv_obj_t * ui_Connect;
void ui_event_labelSearchNetwork1(lv_event_t * e);
extern lv_obj_t * ui_labelSearchNetwork1;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_wifi_search_sized_png);    // assets\wifi_search_sized.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
